# Generated by Django 6.0.3 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is Featured"),
        ),
    ]
